

import 'package:hive_flutter/hive_flutter.dart';

import '../../features/transactions/data/models/transaction_model.dart';

class HiveService {
  HiveService._();

  static const String _txBoxName     = 'transactions';
  static const String _budgetBoxName = 'budgets';

  static Future<void> init() async {
    await Hive.initFlutter();

    // Transaction adapter (generated by build_runner)
    if (!Hive.isAdapterRegistered(TransactionModelAdapter().typeId)) {
      Hive.registerAdapter(TransactionModelAdapter());
    }

    await Hive.openBox<TransactionModel>(_txBoxName);

    // Budget box — uses plain Map<dynamic,dynamic>, no adapter needed
    await Hive.openBox<Map>(_budgetBoxName);
  }

  static Box<TransactionModel> get transactionBox =>
      Hive.box<TransactionModel>(_txBoxName);

  static Box<Map> get budgetBox =>
      Hive.box<Map>(_budgetBoxName);

  static Future<void> clearAll() async {
    await transactionBox.clear();
    await budgetBox.clear();
  }
}