// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DO_oHEyHoy9btjkEjmlFQOU_tEdT3co',
    appId: '1:322190886967:web:c23e2b44595fba2bfe57b2',
    messagingSenderId: '322190886967',
    projectId: 'flow-track-3d1c7',
    authDomain: 'flow-track-3d1c7.firebaseapp.com',
    storageBucket: 'flow-track-3d1c7.firebasestorage.app',
    measurementId: 'G-TBR977SDCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWIdSqAMsP-pbLZVQaUEFyOZYstAa8ZM',
    appId: '1:322190886967:android:4f0494fb908d2d33fe57b2',
    messagingSenderId: '322190886967',
    projectId: 'flow-track-3d1c7',
    storageBucket: 'flow-track-3d1c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCbR8rWqDOkKPn6PDAYYac0SoGaAyoBs',
    appId: '1:322190886967:ios:2d346243d87bd4bafe57b2',
    messagingSenderId: '322190886967',
    projectId: 'flow-track-3d1c7',
    storageBucket: 'flow-track-3d1c7.firebasestorage.app',
    androidClientId: '322190886967-7hcikp7qsmkm4eheu8lcgb0lnjtif89h.apps.googleusercontent.com',
    iosClientId: '322190886967-367os6mt4n24fvl9aijqd7aio8do5fns.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowTrack',
  );

}